server:
  port: 8888
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://imooc:123456@localhost:8761/eureka
#设置路由规则
zuul:
  routes:
    userApi:
      path: /home/**
      serviceId: user
      stripPrefix: false



